# Generated by Django 3.2.15 on 2022-08-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('IP', 'In-progress'), ('CO', 'Completed')], default='IP', max_length=20)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
