# Generated by Django 3.2.15 on 2022-08-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('IP', 'In-progress'), ('CO', 'Completed')], default='IP', max_length=20)),
                ('isArchived', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
